main: me.lewisainsworth.satipoclans.SatipoClan
version: ${project.version}
name: SatipoClans
author: LewisAinsworth
api-version: "1.20"
softdepend: [Vault, PlaceholderAPI]

commands:
  clans:
    description: Comandos principales de los clanes.
    aliases: ${CLANS_ALIASES}
  clansadmin:
    description: Administra el plugin SatipoClans.
    aliases: ${CLANSADMIN_ALIASES}
  scstats:
    description: Muestra estadísticas del jugador.
    aliases: ${SCSTATS_ALIASES}

permissions:
  satipoclans.*:
    description: Todos los permisos del plugin.
    default: op
    children:
      satipoclans.admin: true
      satipoclans.user: true

  satipoclans.admin:
    description: Acceso a comandos administrativos.
    default: op

  satipoclans.user.*:
    description: Acceso a todos los comandos de usuario.
    default: true

  # Permisos específicos para comandos/clanes
  satipoclans.user.create:
    description: Permiso para crear un clan.
    default: true

  satipoclans.user.list:
    description: Permiso para listar clanes.
    default: true

  satipoclans.user.join:
    description: Permiso para unirse a un clan.
    default: true

  satipoclans.user.leave:
    description: Permiso para salir de un clan.
    default: true

  satipoclans.user.disband:
    description: Permiso para disolver un clan.
    default: true

  satipoclans.user.kick:
    description: Permiso para expulsar a un miembro de un clan.
    default: true

  satipoclans.user.ally:
    description: Permiso para gestionar alianzas.
    default: true

  satipoclans.user.ff:
    description: Permiso para configurar fuego amigo.
    default: true

  satipoclans.user.chat:
    description: Permiso para usar chat de clan.
    default: true

  satipoclans.user.stats:
    description: Permiso para ver estadísticas de clanes.
    default: true

  satipoclans.user.invite:
    description: Permiso para invitar jugadores a un clan.
    default: true

  satipoclans.user.accept:
    description: Permiso para aceptar invitaciones a clanes.
    default: true

  satipoclans.user.decline:
    description: Permiso para rechazar invitaciones a clanes.
    default: true

  satipoclans.user.resign:
    description: Permiso para renunciar a un clan.
    default: true

  satipoclans.user.report:
    description: Permiso para reportar clanes.
    default: true