main: me.lewisainsworth.satipoclans.SatipoClan
version: 1.3.7
name: SatipoClans
author: LewisAinsworth
api-version: "1.20"
softdepend: [Vault, PlaceholderAPI]

commands:
  clansadmin:
    description: Administra el plugin SatipoClans.
    aliases: [cla]
  clans:
    description: Comandos principales de los clanes (crear, borrar, invitar, etc.).
    aliases: [cls]
  scstats:
    description: Muestra estadísticas del jugador en SatipoClans.
    aliases: [scs]

permissions:
  satipoclans.*:
    description: Todos los permisos del plugin.
    default: op
    children:
      satipoclans.admin: true
      satipoclans.user: true

  satipoclans.admin:
    description: Acceso a comandos administrativos.
    default: op

  satipoclans.user:
    description: Acceso a comandos de usuario.
    default: true

  # Permisos específicos para comandos/clanes
  satipoclans.create:
    description: Permiso para crear un clan.
    default: true

  satipoclans.list:
    description: Permiso para listar clanes.
    default: true

  satipoclans.join:
    description: Permiso para unirse a un clan.
    default: true

  satipoclans.leave:
    description: Permiso para salir de un clan.
    default: true

  satipoclans.disband:
    description: Permiso para disolver un clan.
    default: op

  satipoclans.kick:
    description: Permiso para expulsar a un miembro de un clan.
    default: op

  satipoclans.ally:
    description: Permiso para gestionar alianzas.
    default: op

  satipoclans.ff:
    description: Permiso para configurar fuego amigo.
    default: op

  satipoclans.chat:
    description: Permiso para usar chat de clan.
    default: true

  satipoclans.stats:
    description: Permiso para ver estadísticas de clanes.
    default: true

  satipoclans.invite:
    description: Permiso para invitar jugadores a un clan.
    default: true

  satipoclans.accept:
    description: Permiso para aceptar invitaciones a clanes.
    default: true

  satipoclans.decline:
    description: Permiso para rechazar invitaciones a clanes.
    default: true

  satipoclans.resign:
    description: Permiso para renunciar a un clan.
    default: true

  satipoclans.report:
    description: Permiso para reportar clanes.
    default: true